name: query_gen
description: A CLI tool for generating models and HTTP client for Dart based on OpenApi Specs(json)
version: 0.1.0
repository: https://github.com/ali2236/query_gen
# homepage: https://www.example.com

environment:
  sdk: '>=2.13.0 <3.0.0'

# dart pub global activate --source path ./
executables:
  query_gen:

dependencies:
  http: ^0.13.0
  code_builder: ^4.1.0
  dart_style: ^2.0.3
  args: ^2.2.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
